embedding:
  cam_dev: "/dev/video2"        
  pixfmt: "YUYV" 
  width: 848
  height: 480
  fps: 6 

  # TinyMobileNet 런타임 스펙 
  input_size: 128
  out_dim: 128
  width_scale: 0.35
  fp16: false                   
  use_depthwise: false         
  use_bn: false             
  pinned: false         

  # img2emb 전용 ROI
  roi_px: [530, 530]
  roi_offset: [90, -130]

  # ONNX 가중치 파일 경로
  weights_path: "model/weights/tinymnet_emb_128d_w035.onnx"

  # 엔드투엔드 워밍업
  e2e_warmup_frames: 6 
  e2e_pregrab: 0   

  # 3뷰 concat 임베딩 설정
  concat3: true   
  mirror_period: 3      
  center_shrink: 0.00        
  mirror_shrink: 0.00      
  
  # rois3 포맷
  rois3:
    - [520, 550,   90, -160, 0]   # center
    - [320, 470, -420, -160, 1]   # left mirror
    - [330, 480,  630, -180, 1]   # right mirror

depth:
  width: 1280      
  height: 720       
  fps: 6
  roi_px: [260, 270]             
  roi_offset: [12, -90]         
  DECIM: 1                       
  PLANE_TAU: 0.004               
  H_MIN_BASE: 0.003               
  H_MAX: 0.4                  
  MIN_OBJ_PIX: 40               
  BOTTOM_ROI_RATIO: 0.20       
  HOLE_FILL: false            
  CORE_MARGIN_PX: 1          
  P_LO: 1.0                  
  P_HI: 99.0                

datamatrix:
  camera: 2                     
  prefer_res: [1920, 1080]      
  prefer_fps: 6
  scan_timeout_s: 2.0            
  decode_interval: 0.20         
  log_every_decode: 0           
  max_backoff: 1.0             
  
  # ROI 목록
  rois:
    - name: ROI_LEFT_MIRROR
      size: [390, 500]
      offset: [-450, -140]
      hflip: true
    - name: ROI_RIGHT_MIRROR
      size: [390, 490]
      offset: [660, -140]
      hflip: true
    - name: ROI_MAIN
      size: [520, 550]
      offset: [90, -160]
      hflip: false

quality:
  q_warn: 0.40      

storage:
  sqlite_path: "pack.db"   

model:
  type: "lgbm"   
  centroids_path: "centroids.npz" 
  lgbm_path: "lgbm.pkl"      
  topk: 3         
  # 선택 옵션
  # top1_threshold: 0.40
  # smooth_window: 3
  # smooth_min_votes: 2
  # min_margin: 0.02
  # centroid_margin_scale: 1500.0

lgbm:
  n_estimators: 200
  num_leaves: 31
  learning_rate: 0.05
  min_data_in_leaf: 10
  feature_fraction: 0.8
  bagging_fraction: 0.8
  bagging_freq: 1
  seed: 42
  cv_k: 5       

# train.py가 자동으로 Grid Search 수행
lgbm_grid:
  learning_rate: [0.03, 0.05, 0.08]
  num_leaves: [31, 63]
  min_data_in_leaf: [10, 20, 40]
  feature_fraction: [0.70, 0.85]
  bagging_fraction: [0.70, 0.90]
  bagging_freq: [1]
  n_estimators: [200, 400]
  max_depth: [-1, 12]   

training:
  min_count: 2                 
  min_q: 0.0           
  
arduino:
  port: "/dev/ttyACM0"         
  baudrate: 9600                
